sensor:

  # Header Outdoor Temperate
  - platform: homeassistant
    entity_id: sensor.hive_current_temperature
    id: hive_current_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(id(outdoor_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.outdoor_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(x)', '(int)round(id(hive_current_temperature).state)' ]

binary_sensor:

 # Mancave lights
  - platform: homeassistant
    id: mancave_lights
    entity_id: light.mancave_lights_socket_1
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: mancave_lights_socket_1
          state:
            checked: !lambda return x;
