sensor:

  # Header Outdoor Temperate
  - platform: homeassistant
    entity_id: sensor.hive_current_temperature
    id: hive_current_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(id(outdoor_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.outdoor_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(x)', '(int)round(id(hive_current_temperature).state)' ]

binary_sensor:

